name: common_lib
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 
  enhanced_containers: ^0.1.0
  cupertino_icons: ^1.0.2
  ezlogin: ^1.0.0

dependency_overrides:
  enhanced_containers:
    path: ../plugins/enhanced_containers
  ezlogin:
    path: ../plugins/ezlogin
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
